Traceback (most recent call last):
  File "c:\users\sllau\appdata\local\pypoetry\cache\virtualenvs\21w44-nz-covid19-vacination-analysis-north-pdjklkmj-py3.9\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\sllau\appdata\local\pypoetry\cache\virtualenvs\21w44-nz-covid19-vacination-analysis-north-pdjklkmj-py3.9\lib\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\sllau\appdata\local\pypoetry\cache\virtualenvs\21w44-nz-covid19-vacination-analysis-north-pdjklkmj-py3.9\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\sllau\appdata\local\pypoetry\cache\virtualenvs\21w44-nz-covid19-vacination-analysis-north-pdjklkmj-py3.9\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "c:\Users\SLLau\.pyenv\pyenv-win\versions\3.9.7\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\users\sllau\appdata\local\pypoetry\cache\virtualenvs\21w44-nz-covid19-vacination-analysis-north-pdjklkmj-py3.9\lib\site-packages\nbclient\client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "c:\users\sllau\appdata\local\pypoetry\cache\virtualenvs\21w44-nz-covid19-vacination-analysis-north-pdjklkmj-py3.9\lib\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\sllau\appdata\local\pypoetry\cache\virtualenvs\21w44-nz-covid19-vacination-analysis-north-pdjklkmj-py3.9\lib\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ethnic_group="European or Other"
fig = px.bar(data.df_all_weeks_no_gender.loc[data.df_all_weeks_no_gender['Ethnic group']==ethnic_group], 
    x="Week ending", 
    y="First dose administered Changed", 
    title=f"{ethnic_group} -  First dose received",
    color='Age Category',
    # facet_col="Gender",
    hover_data=[
        "Ethnic group",
        "Age Category",
        "Population unvaccinated at week start",
        "Population unvaccinated at week end",
        "Population",
        "First dose administered_prior",
        "First dose administered Changed",
        "First dose administered Changed as Percent of unvaccinated Population",
    ],)
plot(fig,filename = 'figure5.html')
display(HTML('figure5.html'))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_7364/167160192.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [0methnic_group[0m[1;33m=[0m[1;34m"European or Other"[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m fig = px.bar(data.df_all_weeks_no_gender.loc[data.df_all_weeks_no_gender['Ethnic group']==ethnic_group], 
[0m[0;32m      3[0m     [0mx[0m[1;33m=[0m[1;34m"Week ending"[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m     [0my[0m[1;33m=[0m[1;34m"First dose administered Changed"[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m     [0mtitle[0m[1;33m=[0m[1;34mf"{ethnic_group} -  First dose received"[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'px' is not defined
NameError: name 'px' is not defined

